services:
  app:
    image: ghcr.io/codewithpreetam/developmentwala-org-017e9c12:latest
    container_name: developmentwala-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOST: 0.0.0.0
    expose:
      - "3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: developmentwala-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app
