/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SubmitScholarshipRouteImport } from './routes/submit-scholarship'
import { Route as SubmitJobRouteImport } from './routes/submit-job'
import { Route as SubmitInternshipRouteImport } from './routes/submit-internship'
import { Route as SubmitGrantRouteImport } from './routes/submit-grant'
import { Route as SubmitFellowshipRouteImport } from './routes/submit-fellowship'
import { Route as SubmitEventRouteImport } from './routes/submit-event'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ScholarshipDetailRouteImport } from './routes/scholarship-detail'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PostOpportunityRouteImport } from './routes/post-opportunity'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InternshipDetailRouteImport } from './routes/internship-detail'
import { Route as GrantDetailRouteImport } from './routes/grant-detail'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FellowshipDetailRouteImport } from './routes/fellowship-detail'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as EventDetailRouteImport } from './routes/event-detail'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as EmployerProfileRouteImport } from './routes/employer-profile'
import { Route as EmployerDashboardRouteImport } from './routes/employer-dashboard'
import { Route as EditOpportunityRouteImport } from './routes/edit-opportunity'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as CandidateDashboardRouteImport } from './routes/candidate-dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScholarshipsIndexRouteImport } from './routes/scholarships.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as InternshipsIndexRouteImport } from './routes/internships.index'
import { Route as GrantsIndexRouteImport } from './routes/grants.index'
import { Route as FellowshipsIndexRouteImport } from './routes/fellowships.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships.$slug'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as InternshipsSlugRouteImport } from './routes/internships.$slug'
import { Route as GrantsSlugRouteImport } from './routes/grants.$slug'
import { Route as FellowshipsSlugRouteImport } from './routes/fellowships.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as ApiPublicRssDotxmlRouteImport } from './routes/api/public/rss[.]xml'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1.$'
import { Route as ApiAuthLinkedinStartRouteImport } from './routes/api/auth.linkedin.start'
import { Route as ApiAuthLinkedinCallbackRouteImport } from './routes/api/auth.linkedin.callback'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitScholarshipRoute = SubmitScholarshipRouteImport.update({
  id: '/submit-scholarship',
  path: '/submit-scholarship',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitJobRoute = SubmitJobRouteImport.update({
  id: '/submit-job',
  path: '/submit-job',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitInternshipRoute = SubmitInternshipRouteImport.update({
  id: '/submit-internship',
  path: '/submit-internship',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitGrantRoute = SubmitGrantRouteImport.update({
  id: '/submit-grant',
  path: '/submit-grant',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitFellowshipRoute = SubmitFellowshipRouteImport.update({
  id: '/submit-fellowship',
  path: '/submit-fellowship',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitEventRoute = SubmitEventRouteImport.update({
  id: '/submit-event',
  path: '/submit-event',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipDetailRoute = ScholarshipDetailRouteImport.update({
  id: '/scholarship-detail',
  path: '/scholarship-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostOpportunityRoute = PostOpportunityRouteImport.update({
  id: '/post-opportunity',
  path: '/post-opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipDetailRoute = InternshipDetailRouteImport.update({
  id: '/internship-detail',
  path: '/internship-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantDetailRoute = GrantDetailRouteImport.update({
  id: '/grant-detail',
  path: '/grant-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipDetailRoute = FellowshipDetailRouteImport.update({
  id: '/fellowship-detail',
  path: '/fellowship-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDetailRoute = EventDetailRouteImport.update({
  id: '/event-detail',
  path: '/event-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerProfileRoute = EmployerProfileRouteImport.update({
  id: '/employer-profile',
  path: '/employer-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer-dashboard',
  path: '/employer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditOpportunityRoute = EditOpportunityRouteImport.update({
  id: '/edit-opportunity',
  path: '/edit-opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate-dashboard',
  path: '/candidate-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIndexRoute = ScholarshipsIndexRouteImport.update({
  id: '/scholarships/',
  path: '/scholarships/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsIndexRoute = InternshipsIndexRouteImport.update({
  id: '/internships/',
  path: '/internships/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsIndexRoute = GrantsIndexRouteImport.update({
  id: '/grants/',
  path: '/grants/',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipsIndexRoute = FellowshipsIndexRouteImport.update({
  id: '/fellowships/',
  path: '/fellowships/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/scholarships/$slug',
  path: '/scholarships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsSlugRoute = InternshipsSlugRouteImport.update({
  id: '/internships/$slug',
  path: '/internships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsSlugRoute = GrantsSlugRouteImport.update({
  id: '/grants/$slug',
  path: '/grants/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipsSlugRoute = FellowshipsSlugRouteImport.update({
  id: '/fellowships/$slug',
  path: '/fellowships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRssDotxmlRoute = ApiPublicRssDotxmlRouteImport.update({
  id: '/api/public/rss.xml',
  path: '/api/public/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLinkedinStartRoute = ApiAuthLinkedinStartRouteImport.update({
  id: '/api/auth/linkedin/start',
  path: '/api/auth/linkedin/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLinkedinCallbackRoute = ApiAuthLinkedinCallbackRouteImport.update({
  id: '/api/auth/linkedin/callback',
  path: '/api/auth/linkedin/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/candidate-dashboard': typeof CandidateDashboardRoute
  '/choose-role': typeof ChooseRoleRoute
  '/contact': typeof ContactRoute
  '/edit-opportunity': typeof EditOpportunityRoute
  '/employer-dashboard': typeof EmployerDashboardRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/employers': typeof EmployersRoute
  '/event-detail': typeof EventDetailRoute
  '/featured': typeof FeaturedRoute
  '/fellowship-detail': typeof FellowshipDetailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grant-detail': typeof GrantDetailRoute
  '/internship-detail': typeof InternshipDetailRoute
  '/legal': typeof LegalRoute
  '/post-opportunity': typeof PostOpportunityRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scholarship-detail': typeof ScholarshipDetailRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit-event': typeof SubmitEventRoute
  '/submit-fellowship': typeof SubmitFellowshipRoute
  '/submit-grant': typeof SubmitGrantRoute
  '/submit-internship': typeof SubmitInternshipRoute
  '/submit-job': typeof SubmitJobRoute
  '/submit-scholarship': typeof SubmitScholarshipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/fellowships/$slug': typeof FellowshipsSlugRoute
  '/grants/$slug': typeof GrantsSlugRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/fellowships/': typeof FellowshipsIndexRoute
  '/grants/': typeof GrantsIndexRoute
  '/internships/': typeof InternshipsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/auth/linkedin/start': typeof ApiAuthLinkedinStartRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/candidate-dashboard': typeof CandidateDashboardRoute
  '/choose-role': typeof ChooseRoleRoute
  '/contact': typeof ContactRoute
  '/edit-opportunity': typeof EditOpportunityRoute
  '/employer-dashboard': typeof EmployerDashboardRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/employers': typeof EmployersRoute
  '/event-detail': typeof EventDetailRoute
  '/featured': typeof FeaturedRoute
  '/fellowship-detail': typeof FellowshipDetailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grant-detail': typeof GrantDetailRoute
  '/internship-detail': typeof InternshipDetailRoute
  '/legal': typeof LegalRoute
  '/post-opportunity': typeof PostOpportunityRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scholarship-detail': typeof ScholarshipDetailRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit-event': typeof SubmitEventRoute
  '/submit-fellowship': typeof SubmitFellowshipRoute
  '/submit-grant': typeof SubmitGrantRoute
  '/submit-internship': typeof SubmitInternshipRoute
  '/submit-job': typeof SubmitJobRoute
  '/submit-scholarship': typeof SubmitScholarshipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/fellowships/$slug': typeof FellowshipsSlugRoute
  '/grants/$slug': typeof GrantsSlugRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/events': typeof EventsIndexRoute
  '/fellowships': typeof FellowshipsIndexRoute
  '/grants': typeof GrantsIndexRoute
  '/internships': typeof InternshipsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/scholarships': typeof ScholarshipsIndexRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/auth/linkedin/start': typeof ApiAuthLinkedinStartRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/candidate-dashboard': typeof CandidateDashboardRoute
  '/choose-role': typeof ChooseRoleRoute
  '/contact': typeof ContactRoute
  '/edit-opportunity': typeof EditOpportunityRoute
  '/employer-dashboard': typeof EmployerDashboardRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/employers': typeof EmployersRoute
  '/event-detail': typeof EventDetailRoute
  '/featured': typeof FeaturedRoute
  '/fellowship-detail': typeof FellowshipDetailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grant-detail': typeof GrantDetailRoute
  '/internship-detail': typeof InternshipDetailRoute
  '/legal': typeof LegalRoute
  '/post-opportunity': typeof PostOpportunityRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scholarship-detail': typeof ScholarshipDetailRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit-event': typeof SubmitEventRoute
  '/submit-fellowship': typeof SubmitFellowshipRoute
  '/submit-grant': typeof SubmitGrantRoute
  '/submit-internship': typeof SubmitInternshipRoute
  '/submit-job': typeof SubmitJobRoute
  '/submit-scholarship': typeof SubmitScholarshipRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/fellowships/$slug': typeof FellowshipsSlugRoute
  '/grants/$slug': typeof GrantsSlugRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/fellowships/': typeof FellowshipsIndexRoute
  '/grants/': typeof GrantsIndexRoute
  '/internships/': typeof InternshipsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/auth/linkedin/start': typeof ApiAuthLinkedinStartRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/admin-login'
    | '/candidate-dashboard'
    | '/choose-role'
    | '/contact'
    | '/edit-opportunity'
    | '/employer-dashboard'
    | '/employer-profile'
    | '/employers'
    | '/event-detail'
    | '/featured'
    | '/fellowship-detail'
    | '/forgot-password'
    | '/grant-detail'
    | '/internship-detail'
    | '/legal'
    | '/post-opportunity'
    | '/pricing'
    | '/privacy-policy'
    | '/reset-password'
    | '/scholarship-detail'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap'
    | '/sitemap.xml'
    | '/submit-event'
    | '/submit-fellowship'
    | '/submit-grant'
    | '/submit-internship'
    | '/submit-job'
    | '/submit-scholarship'
    | '/terms-of-use'
    | '/verify-email'
    | '/blog/$slug'
    | '/events/$slug'
    | '/fellowships/$slug'
    | '/grants/$slug'
    | '/internships/$slug'
    | '/jobs/$slug'
    | '/scholarships/$slug'
    | '/blog/'
    | '/events/'
    | '/fellowships/'
    | '/grants/'
    | '/internships/'
    | '/jobs/'
    | '/scholarships/'
    | '/api/public/rss.xml'
    | '/blog/category/$slug'
    | '/api/auth/linkedin/callback'
    | '/api/auth/linkedin/start'
    | '/api/public/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/admin-login'
    | '/candidate-dashboard'
    | '/choose-role'
    | '/contact'
    | '/edit-opportunity'
    | '/employer-dashboard'
    | '/employer-profile'
    | '/employers'
    | '/event-detail'
    | '/featured'
    | '/fellowship-detail'
    | '/forgot-password'
    | '/grant-detail'
    | '/internship-detail'
    | '/legal'
    | '/post-opportunity'
    | '/pricing'
    | '/privacy-policy'
    | '/reset-password'
    | '/scholarship-detail'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap'
    | '/sitemap.xml'
    | '/submit-event'
    | '/submit-fellowship'
    | '/submit-grant'
    | '/submit-internship'
    | '/submit-job'
    | '/submit-scholarship'
    | '/terms-of-use'
    | '/verify-email'
    | '/blog/$slug'
    | '/events/$slug'
    | '/fellowships/$slug'
    | '/grants/$slug'
    | '/internships/$slug'
    | '/jobs/$slug'
    | '/scholarships/$slug'
    | '/blog'
    | '/events'
    | '/fellowships'
    | '/grants'
    | '/internships'
    | '/jobs'
    | '/scholarships'
    | '/api/public/rss.xml'
    | '/blog/category/$slug'
    | '/api/auth/linkedin/callback'
    | '/api/auth/linkedin/start'
    | '/api/public/v1/$'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/admin-login'
    | '/candidate-dashboard'
    | '/choose-role'
    | '/contact'
    | '/edit-opportunity'
    | '/employer-dashboard'
    | '/employer-profile'
    | '/employers'
    | '/event-detail'
    | '/featured'
    | '/fellowship-detail'
    | '/forgot-password'
    | '/grant-detail'
    | '/internship-detail'
    | '/legal'
    | '/post-opportunity'
    | '/pricing'
    | '/privacy-policy'
    | '/reset-password'
    | '/scholarship-detail'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap'
    | '/sitemap.xml'
    | '/submit-event'
    | '/submit-fellowship'
    | '/submit-grant'
    | '/submit-internship'
    | '/submit-job'
    | '/submit-scholarship'
    | '/terms-of-use'
    | '/verify-email'
    | '/blog/$slug'
    | '/events/$slug'
    | '/fellowships/$slug'
    | '/grants/$slug'
    | '/internships/$slug'
    | '/jobs/$slug'
    | '/scholarships/$slug'
    | '/blog/'
    | '/events/'
    | '/fellowships/'
    | '/grants/'
    | '/internships/'
    | '/jobs/'
    | '/scholarships/'
    | '/api/public/rss.xml'
    | '/blog/category/$slug'
    | '/api/auth/linkedin/callback'
    | '/api/auth/linkedin/start'
    | '/api/public/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  ChooseRoleRoute: typeof ChooseRoleRoute
  ContactRoute: typeof ContactRoute
  EditOpportunityRoute: typeof EditOpportunityRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerProfileRoute: typeof EmployerProfileRoute
  EmployersRoute: typeof EmployersRoute
  EventDetailRoute: typeof EventDetailRoute
  FeaturedRoute: typeof FeaturedRoute
  FellowshipDetailRoute: typeof FellowshipDetailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GrantDetailRoute: typeof GrantDetailRoute
  InternshipDetailRoute: typeof InternshipDetailRoute
  LegalRoute: typeof LegalRoute
  PostOpportunityRoute: typeof PostOpportunityRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScholarshipDetailRoute: typeof ScholarshipDetailRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitEventRoute: typeof SubmitEventRoute
  SubmitFellowshipRoute: typeof SubmitFellowshipRoute
  SubmitGrantRoute: typeof SubmitGrantRoute
  SubmitInternshipRoute: typeof SubmitInternshipRoute
  SubmitJobRoute: typeof SubmitJobRoute
  SubmitScholarshipRoute: typeof SubmitScholarshipRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  FellowshipsSlugRoute: typeof FellowshipsSlugRoute
  GrantsSlugRoute: typeof GrantsSlugRoute
  InternshipsSlugRoute: typeof InternshipsSlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FellowshipsIndexRoute: typeof FellowshipsIndexRoute
  GrantsIndexRoute: typeof GrantsIndexRoute
  InternshipsIndexRoute: typeof InternshipsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ScholarshipsIndexRoute: typeof ScholarshipsIndexRoute
  ApiPublicRssDotxmlRoute: typeof ApiPublicRssDotxmlRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  ApiAuthLinkedinCallbackRoute: typeof ApiAuthLinkedinCallbackRoute
  ApiAuthLinkedinStartRoute: typeof ApiAuthLinkedinStartRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-scholarship': {
      id: '/submit-scholarship'
      path: '/submit-scholarship'
      fullPath: '/submit-scholarship'
      preLoaderRoute: typeof SubmitScholarshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-job': {
      id: '/submit-job'
      path: '/submit-job'
      fullPath: '/submit-job'
      preLoaderRoute: typeof SubmitJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-internship': {
      id: '/submit-internship'
      path: '/submit-internship'
      fullPath: '/submit-internship'
      preLoaderRoute: typeof SubmitInternshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-grant': {
      id: '/submit-grant'
      path: '/submit-grant'
      fullPath: '/submit-grant'
      preLoaderRoute: typeof SubmitGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-fellowship': {
      id: '/submit-fellowship'
      path: '/submit-fellowship'
      fullPath: '/submit-fellowship'
      preLoaderRoute: typeof SubmitFellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-event': {
      id: '/submit-event'
      path: '/submit-event'
      fullPath: '/submit-event'
      preLoaderRoute: typeof SubmitEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-detail': {
      id: '/scholarship-detail'
      path: '/scholarship-detail'
      fullPath: '/scholarship-detail'
      preLoaderRoute: typeof ScholarshipDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-opportunity': {
      id: '/post-opportunity'
      path: '/post-opportunity'
      fullPath: '/post-opportunity'
      preLoaderRoute: typeof PostOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internship-detail': {
      id: '/internship-detail'
      path: '/internship-detail'
      fullPath: '/internship-detail'
      preLoaderRoute: typeof InternshipDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grant-detail': {
      id: '/grant-detail'
      path: '/grant-detail'
      fullPath: '/grant-detail'
      preLoaderRoute: typeof GrantDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship-detail': {
      id: '/fellowship-detail'
      path: '/fellowship-detail'
      fullPath: '/fellowship-detail'
      preLoaderRoute: typeof FellowshipDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-detail': {
      id: '/event-detail'
      path: '/event-detail'
      fullPath: '/event-detail'
      preLoaderRoute: typeof EventDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-profile': {
      id: '/employer-profile'
      path: '/employer-profile'
      fullPath: '/employer-profile'
      preLoaderRoute: typeof EmployerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-dashboard': {
      id: '/employer-dashboard'
      path: '/employer-dashboard'
      fullPath: '/employer-dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-opportunity': {
      id: '/edit-opportunity'
      path: '/edit-opportunity'
      fullPath: '/edit-opportunity'
      preLoaderRoute: typeof EditOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-dashboard': {
      id: '/candidate-dashboard'
      path: '/candidate-dashboard'
      fullPath: '/candidate-dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/': {
      id: '/scholarships/'
      path: '/scholarships'
      fullPath: '/scholarships/'
      preLoaderRoute: typeof ScholarshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/': {
      id: '/internships/'
      path: '/internships'
      fullPath: '/internships/'
      preLoaderRoute: typeof InternshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants/': {
      id: '/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof GrantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowships/': {
      id: '/fellowships/'
      path: '/fellowships'
      fullPath: '/fellowships/'
      preLoaderRoute: typeof FellowshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/scholarships/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/$slug': {
      id: '/internships/$slug'
      path: '/internships/$slug'
      fullPath: '/internships/$slug'
      preLoaderRoute: typeof InternshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants/$slug': {
      id: '/grants/$slug'
      path: '/grants/$slug'
      fullPath: '/grants/$slug'
      preLoaderRoute: typeof GrantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowships/$slug': {
      id: '/fellowships/$slug'
      path: '/fellowships/$slug'
      fullPath: '/fellowships/$slug'
      preLoaderRoute: typeof FellowshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss.xml': {
      id: '/api/public/rss.xml'
      path: '/api/public/rss.xml'
      fullPath: '/api/public/rss.xml'
      preLoaderRoute: typeof ApiPublicRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/linkedin/start': {
      id: '/api/auth/linkedin/start'
      path: '/api/auth/linkedin/start'
      fullPath: '/api/auth/linkedin/start'
      preLoaderRoute: typeof ApiAuthLinkedinStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/linkedin/callback': {
      id: '/api/auth/linkedin/callback'
      path: '/api/auth/linkedin/callback'
      fullPath: '/api/auth/linkedin/callback'
      preLoaderRoute: typeof ApiAuthLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  ChooseRoleRoute: ChooseRoleRoute,
  ContactRoute: ContactRoute,
  EditOpportunityRoute: EditOpportunityRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerProfileRoute: EmployerProfileRoute,
  EmployersRoute: EmployersRoute,
  EventDetailRoute: EventDetailRoute,
  FeaturedRoute: FeaturedRoute,
  FellowshipDetailRoute: FellowshipDetailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GrantDetailRoute: GrantDetailRoute,
  InternshipDetailRoute: InternshipDetailRoute,
  LegalRoute: LegalRoute,
  PostOpportunityRoute: PostOpportunityRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScholarshipDetailRoute: ScholarshipDetailRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitEventRoute: SubmitEventRoute,
  SubmitFellowshipRoute: SubmitFellowshipRoute,
  SubmitGrantRoute: SubmitGrantRoute,
  SubmitInternshipRoute: SubmitInternshipRoute,
  SubmitJobRoute: SubmitJobRoute,
  SubmitScholarshipRoute: SubmitScholarshipRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  FellowshipsSlugRoute: FellowshipsSlugRoute,
  GrantsSlugRoute: GrantsSlugRoute,
  InternshipsSlugRoute: InternshipsSlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  FellowshipsIndexRoute: FellowshipsIndexRoute,
  GrantsIndexRoute: GrantsIndexRoute,
  InternshipsIndexRoute: InternshipsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ScholarshipsIndexRoute: ScholarshipsIndexRoute,
  ApiPublicRssDotxmlRoute: ApiPublicRssDotxmlRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  ApiAuthLinkedinCallbackRoute: ApiAuthLinkedinCallbackRoute,
  ApiAuthLinkedinStartRoute: ApiAuthLinkedinStartRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
